name: Trigger auto deployment for hiremeplease-rq-worker

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/hiremeplease-rq-worker-AutoDeployTrigger-d1614b1f-f9e2-4a68-b358-d973dc7399ca.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.HIREMEPLEASERQWORKER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.HIREMEPLEASERQWORKER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.HIREMEPLEASERQWORKER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: hiremeplease.azurecr.io
          registryUsername: ${{ secrets.HIREMEPLEASERQWORKER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.HIREMEPLEASERQWORKER_REGISTRY_PASSWORD }}
          containerAppName: hiremeplease-rq-worker
          resourceGroup: vercel_projects
          imageToBuild: hiremeplease.azurecr.io/hiremeplease-rq-worker:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


